language: node_js
node_js:
  - "lts/*"
cache:
  npm: false
install:
  - npm install

branches:
  only:
    - stable
    - master


jobs:
  include:
    - stage: build
      script:
        - npm run build
    - stage: version
      script:
        - git remote rm origin
        - git remote add origin https://commonlyjs:${GH_TOKEN}@github.com/commonlyjs/commonly-buildtools.git
        - git config --global user.name "commonly buildbot"
        - git config --global user.email "build@commonlyjs.com"
        - git fetch
        - git checkout master
        - npx cmnyversion
    - stage: release
      script:
        - git remote rm origin
        - git remote add origin https://commonlyjs:${GH_TOKEN}@github.com/commonlyjs/commonly-buildtools.git
        - git config --global user.name "commonly buildbot"
        - git config --global user.email "build@commonlyjs.com"
        - git fetch
        - git checkout master
        - bash node_modules/@commonly-buildtools/configuration/ci/enable-npm-publish.sh
        - npx cmnypublish

stages:
  - name: build
  - name: version
    if: branch = master AND type = push AND commit_message =~ ^feat|fix
  - name: release
    if: commit_message =~ ^v([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})(-next.\d)?$

