name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - v*


jobs:

  lint:
    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run lint --if-present

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build --if-present

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run test --if-present
