name: release

on:
  push:
    branches:
      - master
      - staging
      - stable


jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CI: true
      TRAVIS_BRANCH: master

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Install dependencies
        run: |
          npm install
      - name: Configure Git machine user
        run: |
          git config --global user.name "commonly buildbot"
          git config --global user.email "build@commonlyjs.com"
      - name: Checkout directly to branch
        run: |
          git checkout master
          git reset --hard
      - name: Version
        run: |
          npm run version --if-present
      - name: Push modified files to the repository
        run: |
          git push "https://${{github.actor}}:${GITHUB_TOKEN}@github.com/${{github.repository}}.git" HEAD:${{github.ref}} --follow-tags
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish to npm artifactory
        run: |
          npm run publish --if-present
