name: build

on:
  push:
    branches:
      - master
      - staging
      - stable

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Install dependencies
        run: |
          npm install
      - name: Publish to npm artifactory
        run: |
          npm run publish
